spring:
  profiles:
    active: dev

#spring:
#  config:
#    import: optional:configserver:http://localhost:8888
#  application:
#    name: security-service

#logging.level.org.springframework.data.r2dbc=DEBUG
